# Generated by Django 5.0.4 on 2024-04-29 14:00

import main.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_player_league'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='last_seen',
            field=models.BigIntegerField(blank=True, default=main.models.CURRENT_TIME),
        ),
    ]
