# Generated by Django 5.0.4 on 2024-04-29 14:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_league_logo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Meme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('data', models.JSONField()),
                ('coins_per_hour', models.IntegerField()),
                ('upgrade_price', models.IntegerField()),
                ('logo', models.CharField(max_length=1023)),
            ],
        ),
        migrations.AddField(
            model_name='league',
            name='level',
            field=models.IntegerField(default=1, unique=True),
        ),
        migrations.CreateModel(
            name='MemePlayer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purchase_time', models.DateTimeField(auto_now_add=True)),
                ('current_level', models.IntegerField(default=1)),
                ('current_coins_per_hour', models.IntegerField(default=1)),
                ('current_upgrade_cost', models.IntegerField(default=1)),
                ('meme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.meme')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.player')),
            ],
            options={
                'unique_together': {('player', 'meme')},
            },
        ),
    ]
