# Generated by Django 5.0.4 on 2024-04-30 01:59

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_meme_league_level_memeplayer'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='coins_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='team',
            name='logo',
            field=models.CharField(blank=True, max_length=1023, null=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='energy_limit_level',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10000)]),
        ),
        migrations.AlterField(
            model_name='player',
            name='multitap_level',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10000)]),
        ),
        migrations.AlterField(
            model_name='player',
            name='recharging_speed_level',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10000)]),
        ),
    ]
