# Generated by Django 5.0.4 on 2024-04-30 02:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_team_coins_count_team_logo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='total_coins_per_hour',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
